# Generated by Django 3.2 on 2021-04-14 22:04

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.CharField(default=game.models.randomgame, max_length=10, null=True)),
                ('gamer', models.CharField(default=game.models.randomgame, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Computer and Player',
            },
        ),
    ]
