# Generated by Django 3.2 on 2021-04-16 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_gamemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModelYourself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.CharField(default=game.models.randomgame, max_length=10, null=True)),
                ('gamer', models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors')], max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
